apiVersion: v1
kind: Service
metadata:
  name: argocd-app-svc
  labels:
    app: argocd-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30001
  selector:
    app: argocd-demo
    type: argocd-demo
